# -*- coding: utf-8 -*-
# config.yaml
# Configuration file for seisplot.py

# 3D inline or xline, ignored for 2D data
# Fractions, eg 0.3, are interpreted as fraction of volume in that direction.
direction: xline
number: 5

# Side label side
sidelabel: right

# Traces per inch   (less -> bigger plot)
tpi: 50

# Inches per second (more -> bigger plot)
ips: 3

# Wiggle skips (1 -> no skips, 2 -> every 2nd trace, etc.)
skip: 1

# Seismic data display parameters (wiggle, varden, both):
display: both

# Multiplication factor for amplitudes 
gain: 2

# Percentile to clip amplitude at for display and for histogram. 
percentile: 99.0

# Wiggle fill: RGB, 0-255, opacity: 0-1
colour: 
  - 0
  - 0
  - 0
opacity: 0.67

# Wiggle plot lineweight
lineweight: 0.2

# Colormap for variable density
# e.g. matplotlib colourbars: Greys (black to white), RdBu, RdGy, RdYlBu, seismic, etc.
# See more at http://matplotlib.org/examples/color/colormaps_reference.html
cmap: Greys

# Fontsize
fontsize: 10

# Watermark
#watermark_text: © A Seismic Company
#watermark_size: 16
#watermark_family: serif   # sans-serif, serif, cursive, fantasy, monospace
#watermark_style: normal   # normal, italic, oblique
#watermark_weight: normal  # normal, light, medium, semibold, bold, heavy, black
#watermark_colour: black
#watermark_alpha: 0.5
#watermark_angle: 33  # degrees
#watermark_cols: 4  # in x direction
#watermark_rows: 8  # in x direction

# Stupid things
stain_paper: no
coffee_rings: 0
scribble: no

# Output resolution
dpi: 300
# Plot filename title
fname_title: False